### ISSUE TITLE
inkscape2pcb not working for known good svg

### ISSUE THREAD

**Issue by celem** [erichVK5/inkscape2pcb#1]
I cannot get inkscape2pcb to work. All that I see is a few blobs.
Below are links for the original svg as well as the lht and fp files produced.
This is a shape that I successfully used in 2012 using geda PCB - using the eps/pstoedit method.

Using inkscape version 0.92.2

svg:
https://pastebin.com/c7uZqyLu

lht produced:
https://pastebin.com/sDC2tbmv

fp produced:
https://pastebin.com/Vrzzu0P4

**Comment by erichVK5** [comment]
The conversion script can only process paths that are given to it by Inkscape.

You need to select complex objects and then convert them to paths before exporting.

You can do this with the menu item:

Path->ObjectToPath

or apparently 

Shift+Ctrl+C

Then the File->SaveAs  dialogue will export the elements.

Cheers,

Erich
