### ISSUE TITLE
Importing in to KiCAD?

### ISSUE THREAD

**Issue by tobiasbp** [erichVK5/inkscape2pcb#2]
Readme says the exported files can be imported in to KiCAD.

I do not see the file formats (.fp & .lht) on this list:
http://kicad-pcb.org/help/file-formats/

 I can also not find a way to import them in to pcbnew. Any suggestions? 

Thank you,
Tobias

**Comment by erichVK5** [comment]
Sorry for the delayed response I usually use pcb-rnd which loads the footprints simply with File:Open etc...

I have fired up kicad's pcbnew in a standalone mode and found that the footprint has to be  imported from within the module editor. There is no other way to import it from the file menu or from the library browser/library configuration menu in pcbnew.

Thanks for your query. I will amend the Readme to explain this for Kicad users. 

Enjoy responsibly!!
