### ISSUE TITLE
Stoopid newbie query

### ISSUE THREAD

**Issue by niftyprose** [erichVK5/inkscape2pcb#3]
Erich, sorry, I think I'm doing something wrong.

I downloaded your scripts and used sudo to move them to Inkscape's extension folder. I could see all the other scripts, so I know I got the right folder. I relaunched the program. No .fp option.

I looked at the file ownership and permissions, and used chown to change from my user to root. Nothing. 

I used chmod to set to 755. Still nothing.

Can you help, please?

Best WM / Niftyprose

**Comment by erichVK5** [comment]
First of all, check that you downloaded the raw script files... If you did

 Right click ... Save as ... 

In the browser, it will have downloaded a bunch of html wrapped around the actual script files.

git clone  or  the downloading a zip option  are the easiest ways to get the raw files.

You seem to have done everything right with permissions, so the first thing is to check the script files aren't corrupted.

See how you go!

**Comment by niftyprose** [comment]
Thanks Erich. I actually moved on to a differenbt solution now but if I go
back to GEDA I will try what you said... Best, W.
