### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by Supermagnum** [erichVK5/inkscape2pcb#4]
File "geda_pcb_output.py", line 59
    print ''.join(self.fp)
          ^
SyntaxError: invalid syntax

That results in "unable to save file.

Inkscape version is: 1.0 (1.0+r73+1)

OS: Linux mint 20.
cpu :
AMD Ryzen 7 2700 Eight-Core Processor

**Comment by erichVK5** [comment]
I have not had a chance to modify the code for inkscape version1.0, as I do not have a box running it yet.

The changes to the python internals break < 1.0 compatible plugins.

I will put it on my todo list.

**Comment by Supermagnum** [comment]
👍

**Comment by Chiller2019** [comment]
1.1 still

**Comment by erichVK5** [comment]
Even though my LTS distro still ships Inkscape 0.9, I installed Inkscape v1.1 and upgraded the scripts to work with Inkscape v1.1

My understanding (based on random musings found in forums, google searches and error messages, i.e. not much developer documentation) is that they should also work for v1.0, as the v0.9 to v1.0 transition was the API change which deprecated a lot of things, along with a python 2.x - 3.x transition.

Please test.

I will do the pcb-rnd exporter next. The pcb-rnd exporter is more feature rich, as it also exports paths as polygons if they are non intersecting, which are supported in pcb-rnd footprints. pcb-rnd also has gtk4 support, as well as text in footprints.

**Comment by erichVK5** [comment]
the pcb-rnd exporter has now been updated as well.
